#/usr/bin/env sh

DESKTOP="org.gnome.desktop.wm.keybindings"
SHELL="org.gnome.shell.keybindings"
MUTTER="org.gnome.mutter.keybindings"

gsettings set $DESKTOP switch-to-workspace-left "['<Super>u']"
gsettings set $DESKTOP switch-to-workspace-right "['<Super>i']"
gsettings set $DESKTOP minimize "[]"
gsettings set $DESKTOP switch-applications "['<Super>Tab','<Alt>Tab','<Super>l']"
gsettings set $DESKTOP switch-applications-backward "['<Super>h']"
gsettings set $DESKTOP switch-group "['<Super>Above_Tab','<Alt>Above_Tab','<Super>k']"

#gsettings set $DESKTOP switch-applications-backward "['<Shift><Super>Tab', '<Super>j']"
#gsettings set $DESKTOP switch-group-backward "['<Super><Shift>Above_Tab', '<Super><Shift>k']"

#gsettings set $SHELL switch-to-application-1 "[]"
#gsettings set $SHELL switch-to-application-2 "[]"
#gsettings set $SHELL switch-to-application-3 "[]"
#gsettings set $SHELL switch-to-application-4 "[]"
#gsettings set $SHELL switch-to-application-5 "[]"
#gsettings set $SHELL switch-to-application-6 "[]"
#gsettings set $SHELL switch-to-application-7 "[]"
#gsettings set $SHELL switch-to-application-8 "[]"
#gsettings set $SHELL switch-to-application-9 "[]"
#
#
#gsettings set $DESKTOP switch-to-workspace-1 "['<Super>1','<Super>u']"
#gsettings set $DESKTOP switch-to-workspace-2 "['<Super>2', '<Super>i']"
#gsettings set $DESKTOP switch-to-workspace-3 "['<Super>3', '<Super>o']"
#gsettings set $DESKTOP switch-to-workspace-4 "['<Super>4', '<Super>p']"
#gsettings set $DESKTOP switch-to-workspace-5 "['<Super>5']"
#gsettings set $DESKTOP switch-to-workspace-6 "['<Super>6']"
#gsettings set $DESKTOP switch-to-workspace-7 "['<Super>7']"
#gsettings set $DESKTOP switch-to-workspace-8 "['<Super>8']"
#gsettings set $DESKTOP switch-to-workspace-9 "['<Super>9']"
#gsettings set $DESKTOP switch-to-workspace-10 "['<Super>0']"
##
#gsettings set $DESKTOP move-to-workspace-1 "['<Super><Shift>1', '<Super><Shift>u']"
#gsettings set $DESKTOP move-to-workspace-2 "['<Super><Shift>2', '<Super><Shift>i']"
#gsettings set $DESKTOP move-to-workspace-3 "['<Super><Shift>3', '<Super><Shift>o']"
#gsettings set $DESKTOP move-to-workspace-4 "['<Super><Shift>4', '<Super><Shift>p']"
#gsettings set $DESKTOP move-to-workspace-5 "['<Super><Shift>5']"
#gsettings set $DESKTOP move-to-workspace-6 "['<Super><Shift>6']"
#gsettings set $DESKTOP move-to-workspace-7 "['<Super><Shift>7']"
#gsettings set $DESKTOP move-to-workspace-8 "['<Super><Shift>8']"
#gsettings set $DESKTOP move-to-workspace-9 "['<Super><Shift>9']"
#gsettings set $DESKTOP move-to-workspace-10 "['<Super><Shift>0']"
