local opt = vim.opt

opt.clipboard = "unnamedplus"
opt.expandtab = true
opt.formatoptions:remove "o"
opt.ignorecase = true
opt.inccommand = "split"
opt.number = true
opt.pumheight = 20
opt.relativenumber = true
opt.signcolumn = "yes"
opt.smartcase = true
opt.splitbelow = true
opt.splitright = true
opt.updatetime = 250
opt.writebackup = false
opt.writebackup = false
opt.termguicolors = true
opt.swapfile = false
opt.spell = true
opt.spelloptions = "camel"
opt.cmdheight = 0

-- vim.opt.cursorline = true
-- vim.opt.fillchars = "fold: "
-- vim.opt.foldenable = false
-- vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
-- vim.opt.foldmethod = "expr"
-- vim.opt.list = true
-- vim.opt.listchars = "eol:↵,trail:.,tab:>-"
-- vim.opt.softtabstop = 4
-- vim.opt.tabstop = 4
-- vim.opt.termguicolors = true
-- vim.opt.wildmenu = true
-- vim.opt.wildmode = "longest:full,full"
-- vim.opt.wrap = false
-- vim.opt.mouse = "a"
-- vim.opt.laststatus = 2
-- vim.opt.jumpoptions = "stack"
