require('config/vim')
require('config/packer')
require('config/treesitter')
require('config/telescope')
require('config/snippy')
require('config/completion')
require('config/lsp')
require('config/comments')
require('config/statusline')
require('config/trim')
require('config/filetree')
require('config/colorscheme')
require('config/keymappings')
-- require('config/dap')
